<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="PreethaChandru" failures="1" tests="1" name="Test" time="224.927" errors="0" timestamp="2024-12-21T12:26:08 CST">
  <testcase classname="testcase.LoginTestCase" name="LoginTest" time="0.0">
    <failure type="java.lang.RuntimeException" message="java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1">
      <![CDATA[java.lang.RuntimeException: java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
at utilities.TestDataReader.getAllData(TestDataReader.java:72)
at testcase.LoginTestCase.getTestData(LoginTestCase.java:29)
... 25 more
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- LoginTest -->
</testsuite> <!-- Test -->
